table BI_SF_INSTALLED_PRODUCT
	lineageTag: db85b59a-09ec-4896-83d5-a618551d724f

	measure 'Count of NAME % difference from Hours' =
			
			VAR __BASELINE_VALUE = SUM('BI_SV_SALES_TO_INSTALL_DTL'[Hours])
			VAR __VALUE_TO_COMPARE = DISTINCTCOUNT('BI_SF_INSTALLED_PRODUCT'[NAME])
			RETURN
				IF(
					NOT ISBLANK(__VALUE_TO_COMPARE),
					DIVIDE(__BASELINE_VALUE, __BASELINE_VALUE + __VALUE_TO_COMPARE)
				)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7cd62aaa-950a-4050-9217-7b4c4a0d6917

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalPercentageDifference"
				}

	column Id
		dataType: string
		lineageTag: 42f62d56-2468-49e2-973b-50f072a5d580
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 7880aac8-406d-4cec-b988-e94667317f85
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column CreatedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 9d27d5ff-1288-48e2-b06e-0fd8f0b54be8
		summarizeBy: none
		sourceColumn: CreatedDate

		annotation SummarizationSetBy = Automatic

	column SVMXC__Date_Installed__c
		dataType: dateTime
		formatString: Long Date
		lineageTag: f7675a36-5a0f-4f04-b500-9a292ed1415a
		summarizeBy: none
		sourceColumn: SVMXC__Date_Installed__c

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SVMXC__Product_Name__c
		dataType: string
		lineageTag: 142eac22-b2e6-4313-9e49-4382e9c0edee
		summarizeBy: none
		sourceColumn: SVMXC__Product_Name__c

		annotation SummarizationSetBy = Automatic

	column SVMXC__Product__c
		dataType: string
		lineageTag: c7ea9f28-aa8d-460f-9a14-280bc84d170b
		summarizeBy: none
		sourceColumn: SVMXC__Product__c

		annotation SummarizationSetBy = Automatic

	column SVMXC__Service_Contract__c
		dataType: string
		lineageTag: a94bae22-8c57-49ca-85e2-a1a3b2d8c685
		summarizeBy: none
		sourceColumn: SVMXC__Service_Contract__c

		annotation SummarizationSetBy = Automatic

	column SVMXC__Site__c
		dataType: string
		lineageTag: ae0853cb-3c03-4615-830a-237f9808fa76
		summarizeBy: none
		sourceColumn: SVMXC__Site__c

		annotation SummarizationSetBy = Automatic

	column SVMXC__Status__c
		dataType: string
		lineageTag: 1685b8de-f04a-4f96-a041-35b369070e0c
		summarizeBy: none
		sourceColumn: SVMXC__Status__c

		annotation SummarizationSetBy = Automatic

	column SVMXC__Warranty_End_Date__c
		dataType: dateTime
		formatString: General Date
		lineageTag: 9a4d2c7d-86c4-4dd0-9074-ebd151c6eba9
		summarizeBy: none
		sourceColumn: SVMXC__Warranty_End_Date__c

		annotation SummarizationSetBy = Automatic

	column SVMXC__Warranty_Start_Date__c
		dataType: dateTime
		formatString: General Date
		lineageTag: 23f19d6d-c20e-4111-b87b-b85b3d42e99f
		summarizeBy: none
		sourceColumn: SVMXC__Warranty_Start_Date__c

		annotation SummarizationSetBy = Automatic

	column SVMXC__Warranty__c
		dataType: string
		lineageTag: 00b0e071-11f9-40e9-a55e-1e02eadd4ba4
		summarizeBy: none
		sourceColumn: SVMXC__Warranty__c

		annotation SummarizationSetBy = Automatic

	column Product_Line__c
		dataType: string
		lineageTag: 551f58f1-4a85-416b-9340-4fe3ca3d0278
		summarizeBy: none
		sourceColumn: Product_Line__c

		annotation SummarizationSetBy = Automatic

	column isPrinter__c
		dataType: int64
		formatString: 0
		lineageTag: bfc1d1cf-a13d-47ae-b3a6-451713e8b142
		summarizeBy: sum
		sourceColumn: isPrinter__c

		annotation SummarizationSetBy = Automatic

	column is_Active__c
		dataType: int64
		formatString: 0
		lineageTag: 1d506ba7-cfbe-4dd5-beb3-2b7791e8a932
		summarizeBy: sum
		sourceColumn: is_Active__c

		annotation SummarizationSetBy = Automatic

	column Unique_Printer_Serial_nr__c
		dataType: string
		lineageTag: 40253679-269d-4cbf-8cd5-8d523e0bad66
		summarizeBy: none
		sourceColumn: Unique_Printer_Serial_nr__c

		annotation SummarizationSetBy = Automatic

	column Unique_always__c
		dataType: string
		lineageTag: f7a80b7d-674b-45ed-9ea0-1128678632f6
		summarizeBy: none
		sourceColumn: Unique_always__c

		annotation SummarizationSetBy = Automatic

	column Ink_Type__c
		dataType: string
		lineageTag: 83d53ced-0a0f-4ab2-83ed-3ac22f4a4e69
		summarizeBy: none
		sourceColumn: Ink_Type__c

		annotation SummarizationSetBy = Automatic

	column Nozzle__c
		dataType: string
		lineageTag: 226fe60c-70a2-4f81-bdc8-09026e682f8c
		summarizeBy: none
		sourceColumn: Nozzle__c

		annotation SummarizationSetBy = Automatic

	column Trial_Printer__c
		dataType: int64
		formatString: 0
		lineageTag: 511964ed-2d3e-4f45-89de-b37695e53d11
		summarizeBy: sum
		sourceColumn: Trial_Printer__c

		annotation SummarizationSetBy = Automatic

	column isInstalledBase__c
		dataType: int64
		formatString: 0
		lineageTag: ca7e80a2-f524-44a8-af20-01f8841e2c0f
		summarizeBy: sum
		sourceColumn: isInstalledBase__c

		annotation SummarizationSetBy = Automatic

	column Age__c
		dataType: double
		lineageTag: 213434b4-f10a-458e-8411-3a89a804f7e8
		summarizeBy: sum
		sourceColumn: Age__c

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Product_Family__c
		dataType: string
		lineageTag: b87bdaec-d027-4e87-b63c-2de4df41bde1
		summarizeBy: none
		sourceColumn: Product_Family__c

		annotation SummarizationSetBy = Automatic

	column Product_Technology__c
		dataType: string
		lineageTag: c8899bcf-e7a7-4b15-8e78-752c9cf2d524
		summarizeBy: none
		sourceColumn: Product_Technology__c

		annotation SummarizationSetBy = Automatic

	column Software_Version__c
		dataType: string
		lineageTag: 6d3c3133-9ce7-4d17-8c5c-5acc9a999076
		summarizeBy: none
		sourceColumn: Software_Version__c

		annotation SummarizationSetBy = Automatic

	column Printer_Family__c
		dataType: string
		lineageTag: 96133fdd-f7c2-4d1b-a875-9bcf29f700f9
		summarizeBy: none
		sourceColumn: Printer_Family__c

		annotation SummarizationSetBy = Automatic

	column Cloud_Connect_Status__c
		dataType: string
		lineageTag: 43a71695-e179-4c05-9ad2-ae8b6a222476
		summarizeBy: none
		sourceColumn: Cloud_Connect_Status__c

		annotation SummarizationSetBy = Automatic

	column SVMXC__Company__c
		dataType: string
		lineageTag: 94816d5b-8299-4c87-b95e-a79e1bf32a69
		summarizeBy: none
		sourceColumn: SVMXC__Company__c

		annotation SummarizationSetBy = Automatic

	column Contract_Name
		dataType: string
		lineageTag: 6543e870-adf0-4b57-932a-5286090f4b5a
		summarizeBy: none
		sourceColumn: Contract_Name

		annotation SummarizationSetBy = Automatic

	column Contract_Start_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3925187b-7b6b-47b3-9120-b71f95d4d26c
		summarizeBy: none
		sourceColumn: Contract_Start_Date

		annotation SummarizationSetBy = Automatic

	column Contract_End_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 853dace4-3e8e-49b1-8f9a-15d762aa845b
		summarizeBy: none
		sourceColumn: Contract_End_Date

		annotation SummarizationSetBy = Automatic

	column Contract_Active_Flag
		dataType: int64
		formatString: 0
		lineageTag: 131540b4-5b2a-457c-ad35-9e746d19b5fa
		summarizeBy: sum
		sourceColumn: Contract_Active_Flag

		annotation SummarizationSetBy = Automatic

	column Warranty_Status
		dataType: string
		lineageTag: 3a5d9d8a-5083-4555-bc08-4c6a14a7b9d2
		summarizeBy: none
		sourceColumn: Warranty_Status

		annotation SummarizationSetBy = Automatic

	column Contract_Type__c
		dataType: string
		lineageTag: 95861dc3-0814-4e4e-8030-964757bb15ea
		summarizeBy: none
		sourceColumn: Contract_Type__c

		annotation SummarizationSetBy = Automatic

	column 'Install year' = YEAR( BI_SF_INSTALLED_PRODUCT[SVMXC__Date_Installed__c] )
		formatString: 0
		lineageTag: 30e4f9d2-d2cc-44f7-9d05-73ae11aa6b96
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Install Month Number' = MONTH ( BI_SF_INSTALLED_PRODUCT[SVMXC__Date_Installed__c] )
		formatString: 0
		lineageTag: 198c3dfc-83e2-4508-8034-69cec98e02ab
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Install Month' = FORMAT ( BI_SF_INSTALLED_PRODUCT[SVMXC__Date_Installed__c], "MMM" )
		lineageTag: 526436bc-0737-4d17-aabb-8e913b5c7bc0
		summarizeBy: none
		sortByColumn: 'Install Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Install Year Month' =
			
			FORMAT ( BI_SF_INSTALLED_PRODUCT[SVMXC__Date_Installed__c], "YYYY MMM" )
		lineageTag: 9df01f50-32e9-4e6d-9fcc-448dfb5ffc07
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Install Day' = DAY ( BI_SF_INSTALLED_PRODUCT[SVMXC__Date_Installed__c] )
		formatString: 0
		lineageTag: 4318cc14-49bd-4965-afb3-5d1266840e8c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	hierarchy 'Installation Date Hierarchy'
		lineageTag: 69bd2c14-14be-4d1b-be71-0f1bcf3235b0

		level 'Install year'
			lineageTag: 8bf3107e-fa80-4b53-a7b6-ab73fef01848
			column: 'Install year'

		level 'Install Month'
			lineageTag: aa96a1e8-4aa6-474b-bbf6-9137b13c06a8
			column: 'Install Month'

		level SVMXC__Date_Installed__c
			lineageTag: 367cbabd-3567-4aa9-9aeb-2fb16e1cfc62
			column: SVMXC__Date_Installed__c

	partition BI_SF_INSTALLED_PRODUCT-0f8a2e25-4a9b-496a-aaef-03aa451a60e8 = m
		mode: import
		source =
				let
				    // Connect to SQL Server
				    Source = Sql.Database("azwemisqldcoe.0f9aff9ccbfc.database.windows.net", "DCOE", [Query="SELECT I.[Id]#(lf)      ,I.[Name]#(lf)      ,I.[CreatedDate]#(lf)      ,I.[SVMXC__Date_Installed__c]#(lf)      ,I.[SVMXC__Company__c]#(lf)      ,I.[SVMXC__Product_Name__c]#(lf)      ,I.[SVMXC__Product__c]#(lf)      ,I.[SVMXC__Service_Contract__c]#(lf)      ,I.[SVMXC__Site__c]#(lf)      ,I.[SVMXC__Warranty_End_Date__c]#(lf)      ,I.[SVMXC__Warranty_Start_Date__c]#(lf)      ,I.[SVMXC__Warranty__c]#(lf)      ,I.[SVMXC__Status__c]#(lf)      ,I.[Product_Line__c]#(lf)      ,I.[isPrinter__c]#(lf)      ,I.[is_Active__c]#(lf)      ,#(lf)#(tab)#(tab)CASE#(lf)#(tab)#(tab)#(tab)WHEN Last_Warranty_End_Date__c > CAST(GETDATE() AS date)#(lf)#(tab)#(tab)#(tab)#(tab)THEN CONVERT(varchar(10), Last_Warranty_End_Date__c, 23)#(lf)#(tab)#(tab)#(tab)ELSE 'Expired'#(lf)#(tab)#(tab)END AS Warranty_Status#(lf)      ,I.[Unique_Printer_Serial_nr__c]#(lf)      ,I.[Unique_always__c]#(lf)      ,I.[Ink_Type__c]#(lf)      ,I.[Nozzle__c]#(lf)      ,I.[Trial_Printer__c]#(lf)      ,I.[isInstalledBase__c]#(lf)      ,I.[Age__c]#(lf)      ,I.[Product_Family__c]#(lf)      ,I.[Product_Technology__c]#(lf)      ,I.[Software_Version__c]#(lf)      ,I.[Printer_Family__c]#(lf)      ,#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN I.Cloud_Connect_Status__c IS NULL #(lf)#(tab)#(tab)#(tab)#(tab) OR LTRIM(RTRIM(Cloud_Connect_Status__c)) = '' #(lf)#(tab)#(tab)#(tab)THEN 'Cloud Record Unavailable'#(lf)#(tab)#(tab)#(tab)ELSE I.Cloud_Connect_Status__c#(lf)#(tab)#(tab)END AS Cloud_Connect_Status__c#(lf)#(lf)#(tab)  ,C.Name AS Contract_Name#(lf)#(tab)  ,C.SVMXC__Start_Date__c AS Contract_Start_Date#(lf)#(tab)  ,C.End_Date_1__c AS Contract_End_Date#(lf)#(tab)  ,COALESCE(C.SVMXC__Active__c, 0) AS Contract_Active_Flag#(lf)          ,C.Contract_Type__c#(lf)  FROM [DCOE].[dbo].[ods_sf_installed_product] I#(lf)  LEFT JOIN [DCOE].[dbo].[ods_sf_service_maint_contract] C#(lf)  ON I.SVMXC__Service_Contract__c = C.Id#(lf)  WHERE Domino_Sub__c IN ('Domino UK', 'Domino BE/LUX', 'Domino US', 'Domino FR', 'Domino NL', 'Domino CA')", CommandTimeout=#duration(0, 0, 25, 0)]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"SVMXC__Date_Installed__c", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

